#!/bin/sh

# Startup script for machine-dependent executable
# PG, 29.07.2015

# ------ Full path name of program directory ------

f=$0
if [ `echo $f | sed 's,^/.*,+,'` != "+" ]; then f=`which $0`; fi
odir=`pwd`
while [ "`ls -l $f | awk '{ print substr($1,1,1) }'`" = "l" ]; do
  l=`ls -l $f | awk '{ i = NF; print $i }'`
  cd `dirname $f`; cd `dirname $l`; l=`pwd`/`basename $l`
  f=$l
done
cd `dirname $f`
dir=`pwd | sed 's,/src$,,'`
cd "$odir"

# ------ Start executable ------

$dir/`basename $f`.`uname` $*
